### ISSUE TITLE
Test DST for NYC

### ISSUE THREAD

**Issue by bksubhuti** [bksubhuti/buddhist_sun#14]
for dst.. need to check nyc times and solar maps  setting location on emulator to nyc
DST is this date  usually sunday at 12:00 am
Sun, Mar 10, 2024 – Sun, Nov 3, 2024

Here is a link to time and date dot com
https://www.timeanddate.com/sun/usa/new-york?month=11&year=2024

"fall back spring ahead"  So I think the clock will go backwards.. 
So I guess you should check to see that the solar noon goes down 1 hour  from maybe 12 to 11 according to the time.

![image](https://github.com/user-attachments/assets/29d74431-c12e-44e6-b159-4d6860204cd9)

Your clock should automatically change when you go from each day. 
and .. the offset should also change.. (That you can see on the home screen too).  That will mean that Solar Noon will change with it too.
This should take less than 5 minutes considering you can build buddhist sun okay.
testing the two days should be enough.
But if you want to test march 10 in the same way.. then that would be even better.

**Comment by sumbodhi** [comment]
it does

Nov 1:
![image](https://github.com/user-attachments/assets/01128b6d-baea-48c5-9707-66ce84b49c8d)

Nov 5:
![image](https://github.com/user-attachments/assets/699e0c65-81ad-4c6e-a0d6-09944c042ea8)

**Comment by bksubhuti** [comment]
sadhu x 3.. closed.
